// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteDriverOKCode is the HTTP code returned for type DeleteDriverOK
const DeleteDriverOKCode int = 200

/*
DeleteDriverOK OK

swagger:response deleteDriverOK
*/
type DeleteDriverOK struct {
}

// NewDeleteDriverOK creates DeleteDriverOK with default headers values
func NewDeleteDriverOK() *DeleteDriverOK {

	return &DeleteDriverOK{}
}

// WriteResponse to the client
func (o *DeleteDriverOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteDriverBadRequestCode is the HTTP code returned for type DeleteDriverBadRequest
const DeleteDriverBadRequestCode int = 400

/*
DeleteDriverBadRequest Driver does not exist

swagger:response deleteDriverBadRequest
*/
type DeleteDriverBadRequest struct {

	/*
	  In: Body
	*/
	Payload *DeleteDriverBadRequestBody `json:"body,omitempty"`
}

// NewDeleteDriverBadRequest creates DeleteDriverBadRequest with default headers values
func NewDeleteDriverBadRequest() *DeleteDriverBadRequest {

	return &DeleteDriverBadRequest{}
}

// WithPayload adds the payload to the delete driver bad request response
func (o *DeleteDriverBadRequest) WithPayload(payload *DeleteDriverBadRequestBody) *DeleteDriverBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete driver bad request response
func (o *DeleteDriverBadRequest) SetPayload(payload *DeleteDriverBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteDriverBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteDriverUnauthorizedCode is the HTTP code returned for type DeleteDriverUnauthorized
const DeleteDriverUnauthorizedCode int = 401

/*
DeleteDriverUnauthorized Token expired

swagger:response deleteDriverUnauthorized
*/
type DeleteDriverUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *DeleteDriverUnauthorizedBody `json:"body,omitempty"`
}

// NewDeleteDriverUnauthorized creates DeleteDriverUnauthorized with default headers values
func NewDeleteDriverUnauthorized() *DeleteDriverUnauthorized {

	return &DeleteDriverUnauthorized{}
}

// WithPayload adds the payload to the delete driver unauthorized response
func (o *DeleteDriverUnauthorized) WithPayload(payload *DeleteDriverUnauthorizedBody) *DeleteDriverUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete driver unauthorized response
func (o *DeleteDriverUnauthorized) SetPayload(payload *DeleteDriverUnauthorizedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteDriverUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteDriverForbiddenCode is the HTTP code returned for type DeleteDriverForbidden
const DeleteDriverForbiddenCode int = 403

/*
DeleteDriverForbidden Incorrect token

swagger:response deleteDriverForbidden
*/
type DeleteDriverForbidden struct {

	/*
	  In: Body
	*/
	Payload *DeleteDriverForbiddenBody `json:"body,omitempty"`
}

// NewDeleteDriverForbidden creates DeleteDriverForbidden with default headers values
func NewDeleteDriverForbidden() *DeleteDriverForbidden {

	return &DeleteDriverForbidden{}
}

// WithPayload adds the payload to the delete driver forbidden response
func (o *DeleteDriverForbidden) WithPayload(payload *DeleteDriverForbiddenBody) *DeleteDriverForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete driver forbidden response
func (o *DeleteDriverForbidden) SetPayload(payload *DeleteDriverForbiddenBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteDriverForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteDriverInternalServerErrorCode is the HTTP code returned for type DeleteDriverInternalServerError
const DeleteDriverInternalServerErrorCode int = 500

/*
DeleteDriverInternalServerError Unexpected server error

swagger:response deleteDriverInternalServerError
*/
type DeleteDriverInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *DeleteDriverInternalServerErrorBody `json:"body,omitempty"`
}

// NewDeleteDriverInternalServerError creates DeleteDriverInternalServerError with default headers values
func NewDeleteDriverInternalServerError() *DeleteDriverInternalServerError {

	return &DeleteDriverInternalServerError{}
}

// WithPayload adds the payload to the delete driver internal server error response
func (o *DeleteDriverInternalServerError) WithPayload(payload *DeleteDriverInternalServerErrorBody) *DeleteDriverInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete driver internal server error response
func (o *DeleteDriverInternalServerError) SetPayload(payload *DeleteDriverInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteDriverInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
