// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostDriverSingUpCreatedCode is the HTTP code returned for type PostDriverSingUpCreated
const PostDriverSingUpCreatedCode int = 201

/*
PostDriverSingUpCreated Status of authentication

swagger:response postDriverSingUpCreated
*/
type PostDriverSingUpCreated struct {

	/*
	  In: Body
	*/
	Payload *PostDriverSingUpCreatedBody `json:"body,omitempty"`
}

// NewPostDriverSingUpCreated creates PostDriverSingUpCreated with default headers values
func NewPostDriverSingUpCreated() *PostDriverSingUpCreated {

	return &PostDriverSingUpCreated{}
}

// WithPayload adds the payload to the post driver sing up created response
func (o *PostDriverSingUpCreated) WithPayload(payload *PostDriverSingUpCreatedBody) *PostDriverSingUpCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post driver sing up created response
func (o *PostDriverSingUpCreated) SetPayload(payload *PostDriverSingUpCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDriverSingUpCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostDriverSingUpBadRequestCode is the HTTP code returned for type PostDriverSingUpBadRequest
const PostDriverSingUpBadRequestCode int = 400

/*
PostDriverSingUpBadRequest Incorrect input data or user already exist

swagger:response postDriverSingUpBadRequest
*/
type PostDriverSingUpBadRequest struct {

	/*
	  In: Body
	*/
	Payload *PostDriverSingUpBadRequestBody `json:"body,omitempty"`
}

// NewPostDriverSingUpBadRequest creates PostDriverSingUpBadRequest with default headers values
func NewPostDriverSingUpBadRequest() *PostDriverSingUpBadRequest {

	return &PostDriverSingUpBadRequest{}
}

// WithPayload adds the payload to the post driver sing up bad request response
func (o *PostDriverSingUpBadRequest) WithPayload(payload *PostDriverSingUpBadRequestBody) *PostDriverSingUpBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post driver sing up bad request response
func (o *PostDriverSingUpBadRequest) SetPayload(payload *PostDriverSingUpBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDriverSingUpBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostDriverSingUpInternalServerErrorCode is the HTTP code returned for type PostDriverSingUpInternalServerError
const PostDriverSingUpInternalServerErrorCode int = 500

/*
PostDriverSingUpInternalServerError Unexpected server error

swagger:response postDriverSingUpInternalServerError
*/
type PostDriverSingUpInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *PostDriverSingUpInternalServerErrorBody `json:"body,omitempty"`
}

// NewPostDriverSingUpInternalServerError creates PostDriverSingUpInternalServerError with default headers values
func NewPostDriverSingUpInternalServerError() *PostDriverSingUpInternalServerError {

	return &PostDriverSingUpInternalServerError{}
}

// WithPayload adds the payload to the post driver sing up internal server error response
func (o *PostDriverSingUpInternalServerError) WithPayload(payload *PostDriverSingUpInternalServerErrorBody) *PostDriverSingUpInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post driver sing up internal server error response
func (o *PostDriverSingUpInternalServerError) SetPayload(payload *PostDriverSingUpInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDriverSingUpInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
