// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"
)

// NewPostDriverSingUpParams creates a new PostDriverSingUpParams object
//
// There are no default values defined in the spec.
func NewPostDriverSingUpParams() PostDriverSingUpParams {

	return PostDriverSingUpParams{}
}

// PostDriverSingUpParams contains all the bound params for the post driver sing up operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostDriverSingUp
type PostDriverSingUpParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Authentication info
	  Required: true
	  In: body
	*/
	Input PostDriverSingUpBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostDriverSingUpParams() beforehand.
func (o *PostDriverSingUpParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body PostDriverSingUpBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("input", "body", ""))
			} else {
				res = append(res, errors.NewParseError("input", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Input = body
			}
		}
	} else {
		res = append(res, errors.Required("input", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
