// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostDriverRefreshOKCode is the HTTP code returned for type PostDriverRefreshOK
const PostDriverRefreshOKCode int = 200

/*
PostDriverRefreshOK Access token

swagger:response postDriverRefreshOK
*/
type PostDriverRefreshOK struct {

	/*
	  In: Body
	*/
	Payload *PostDriverRefreshOKBody `json:"body,omitempty"`
}

// NewPostDriverRefreshOK creates PostDriverRefreshOK with default headers values
func NewPostDriverRefreshOK() *PostDriverRefreshOK {

	return &PostDriverRefreshOK{}
}

// WithPayload adds the payload to the post driver refresh o k response
func (o *PostDriverRefreshOK) WithPayload(payload *PostDriverRefreshOKBody) *PostDriverRefreshOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post driver refresh o k response
func (o *PostDriverRefreshOK) SetPayload(payload *PostDriverRefreshOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDriverRefreshOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostDriverRefreshUnauthorizedCode is the HTTP code returned for type PostDriverRefreshUnauthorized
const PostDriverRefreshUnauthorizedCode int = 401

/*
PostDriverRefreshUnauthorized Token expired

swagger:response postDriverRefreshUnauthorized
*/
type PostDriverRefreshUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *PostDriverRefreshUnauthorizedBody `json:"body,omitempty"`
}

// NewPostDriverRefreshUnauthorized creates PostDriverRefreshUnauthorized with default headers values
func NewPostDriverRefreshUnauthorized() *PostDriverRefreshUnauthorized {

	return &PostDriverRefreshUnauthorized{}
}

// WithPayload adds the payload to the post driver refresh unauthorized response
func (o *PostDriverRefreshUnauthorized) WithPayload(payload *PostDriverRefreshUnauthorizedBody) *PostDriverRefreshUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post driver refresh unauthorized response
func (o *PostDriverRefreshUnauthorized) SetPayload(payload *PostDriverRefreshUnauthorizedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDriverRefreshUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostDriverRefreshForbiddenCode is the HTTP code returned for type PostDriverRefreshForbidden
const PostDriverRefreshForbiddenCode int = 403

/*
PostDriverRefreshForbidden Wrong signature

swagger:response postDriverRefreshForbidden
*/
type PostDriverRefreshForbidden struct {

	/*
	  In: Body
	*/
	Payload *PostDriverRefreshForbiddenBody `json:"body,omitempty"`
}

// NewPostDriverRefreshForbidden creates PostDriverRefreshForbidden with default headers values
func NewPostDriverRefreshForbidden() *PostDriverRefreshForbidden {

	return &PostDriverRefreshForbidden{}
}

// WithPayload adds the payload to the post driver refresh forbidden response
func (o *PostDriverRefreshForbidden) WithPayload(payload *PostDriverRefreshForbiddenBody) *PostDriverRefreshForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post driver refresh forbidden response
func (o *PostDriverRefreshForbidden) SetPayload(payload *PostDriverRefreshForbiddenBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDriverRefreshForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostDriverRefreshInternalServerErrorCode is the HTTP code returned for type PostDriverRefreshInternalServerError
const PostDriverRefreshInternalServerErrorCode int = 500

/*
PostDriverRefreshInternalServerError Unexpected server error

swagger:response postDriverRefreshInternalServerError
*/
type PostDriverRefreshInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *PostDriverRefreshInternalServerErrorBody `json:"body,omitempty"`
}

// NewPostDriverRefreshInternalServerError creates PostDriverRefreshInternalServerError with default headers values
func NewPostDriverRefreshInternalServerError() *PostDriverRefreshInternalServerError {

	return &PostDriverRefreshInternalServerError{}
}

// WithPayload adds the payload to the post driver refresh internal server error response
func (o *PostDriverRefreshInternalServerError) WithPayload(payload *PostDriverRefreshInternalServerErrorBody) *PostDriverRefreshInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post driver refresh internal server error response
func (o *PostDriverRefreshInternalServerError) SetPayload(payload *PostDriverRefreshInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDriverRefreshInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
