// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostDriverSingInOKCode is the HTTP code returned for type PostDriverSingInOK
const PostDriverSingInOKCode int = 200

/*
PostDriverSingInOK Access token

swagger:response postDriverSingInOK
*/
type PostDriverSingInOK struct {

	/*
	  In: Body
	*/
	Payload *PostDriverSingInOKBody `json:"body,omitempty"`
}

// NewPostDriverSingInOK creates PostDriverSingInOK with default headers values
func NewPostDriverSingInOK() *PostDriverSingInOK {

	return &PostDriverSingInOK{}
}

// WithPayload adds the payload to the post driver sing in o k response
func (o *PostDriverSingInOK) WithPayload(payload *PostDriverSingInOKBody) *PostDriverSingInOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post driver sing in o k response
func (o *PostDriverSingInOK) SetPayload(payload *PostDriverSingInOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDriverSingInOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostDriverSingInBadRequestCode is the HTTP code returned for type PostDriverSingInBadRequest
const PostDriverSingInBadRequestCode int = 400

/*
PostDriverSingInBadRequest Incorrect input data

swagger:response postDriverSingInBadRequest
*/
type PostDriverSingInBadRequest struct {

	/*
	  In: Body
	*/
	Payload *PostDriverSingInBadRequestBody `json:"body,omitempty"`
}

// NewPostDriverSingInBadRequest creates PostDriverSingInBadRequest with default headers values
func NewPostDriverSingInBadRequest() *PostDriverSingInBadRequest {

	return &PostDriverSingInBadRequest{}
}

// WithPayload adds the payload to the post driver sing in bad request response
func (o *PostDriverSingInBadRequest) WithPayload(payload *PostDriverSingInBadRequestBody) *PostDriverSingInBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post driver sing in bad request response
func (o *PostDriverSingInBadRequest) SetPayload(payload *PostDriverSingInBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDriverSingInBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostDriverSingInForbiddenCode is the HTTP code returned for type PostDriverSingInForbidden
const PostDriverSingInForbiddenCode int = 403

/*
PostDriverSingInForbidden Wrong phone number or password

swagger:response postDriverSingInForbidden
*/
type PostDriverSingInForbidden struct {

	/*
	  In: Body
	*/
	Payload *PostDriverSingInForbiddenBody `json:"body,omitempty"`
}

// NewPostDriverSingInForbidden creates PostDriverSingInForbidden with default headers values
func NewPostDriverSingInForbidden() *PostDriverSingInForbidden {

	return &PostDriverSingInForbidden{}
}

// WithPayload adds the payload to the post driver sing in forbidden response
func (o *PostDriverSingInForbidden) WithPayload(payload *PostDriverSingInForbiddenBody) *PostDriverSingInForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post driver sing in forbidden response
func (o *PostDriverSingInForbidden) SetPayload(payload *PostDriverSingInForbiddenBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDriverSingInForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostDriverSingInInternalServerErrorCode is the HTTP code returned for type PostDriverSingInInternalServerError
const PostDriverSingInInternalServerErrorCode int = 500

/*
PostDriverSingInInternalServerError Unexpected server error

swagger:response postDriverSingInInternalServerError
*/
type PostDriverSingInInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *PostDriverSingInInternalServerErrorBody `json:"body,omitempty"`
}

// NewPostDriverSingInInternalServerError creates PostDriverSingInInternalServerError with default headers values
func NewPostDriverSingInInternalServerError() *PostDriverSingInInternalServerError {

	return &PostDriverSingInInternalServerError{}
}

// WithPayload adds the payload to the post driver sing in internal server error response
func (o *PostDriverSingInInternalServerError) WithPayload(payload *PostDriverSingInInternalServerErrorBody) *PostDriverSingInInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post driver sing in internal server error response
func (o *PostDriverSingInInternalServerError) SetPayload(payload *PostDriverSingInInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDriverSingInInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
