// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "InnoTaxi Driver API",
    "version": "1.0"
  },
  "paths": {
    "/driver/sing-up": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "auth"
        ],
        "summary": "user authentication",
        "parameters": [
          {
            "description": "Authentication info",
            "name": "input",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                },
                "name": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                },
                "password": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                },
                "phone_number": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                },
                "taxi_type": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Status of authentication",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Incorrect input data or user already exist",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Unexpected server error",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "InnoTaxi Driver API",
    "version": "1.0"
  },
  "paths": {
    "/driver/sing-up": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "auth"
        ],
        "summary": "user authentication",
        "parameters": [
          {
            "description": "Authentication info",
            "name": "input",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                },
                "name": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                },
                "password": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                },
                "phone_number": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                },
                "taxi_type": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Status of authentication",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Incorrect input data or user already exist",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Unexpected server error",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}`))
}
