// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "InnoTaxi Driver API",
    "version": "1.0"
  },
  "paths": {
    "/driver": {
      "delete": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver"
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Driver does not exist",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Token expired",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "403": {
            "description": "Incorrect token",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Unexpected server error",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/driver/refresh": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "auth"
        ],
        "parameters": [
          {
            "description": "Refresh access token",
            "name": "input",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "refresh_token": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Access token",
            "schema": {
              "type": "object",
              "properties": {
                "access_token": {
                  "type": "string"
                },
                "refresh_token": {
                  "type": "string"
                }
              }
            },
            "examples": {
              "properties": {
                "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzUxNjcyODksInVzZXJfaWQiOjF9.gCvkF6ZWJ5c_zA79ILuuEwvkrkn1kOU1Y-Mgr3K2NiM",
                "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Nzc3NTc0OTcsInVzZXJfaWQiOjF9.H5s2JnmjUseUqWFYiLzfYWrlIfa-4dDtd3H2LS5R6IM"
              },
              "type": "object"
            }
          },
          "401": {
            "description": "Token expired",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "403": {
            "description": "Wrong signature",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Unexpected server error",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/driver/sing-in": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "auth"
        ],
        "parameters": [
          {
            "description": "Authentication info",
            "name": "input",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "password": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                },
                "phone_number": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Access token",
            "schema": {
              "type": "object",
              "properties": {
                "access_token": {
                  "type": "string"
                },
                "refresh_token": {
                  "type": "string"
                }
              }
            },
            "examples": {
              "properties": {
                "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzUxNjcyODksInVzZXJfaWQiOjF9.gCvkF6ZWJ5c_zA79ILuuEwvkrkn1kOU1Y-Mgr3K2NiM",
                "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Nzc3NTc0OTcsInVzZXJfaWQiOjF9.H5s2JnmjUseUqWFYiLzfYWrlIfa-4dDtd3H2LS5R6IM"
              },
              "type": "object"
            }
          },
          "400": {
            "description": "Incorrect input data",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "403": {
            "description": "Wrong phone number or password",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Unexpected server error",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/driver/sing-up": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "auth"
        ],
        "summary": "user authentication",
        "parameters": [
          {
            "description": "Authentication info",
            "name": "input",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                },
                "name": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                },
                "password": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                },
                "phone_number": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                },
                "taxi_type": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Status of authentication",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Incorrect input data or user already exist",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Unexpected server error",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "InnoTaxi Driver API",
    "version": "1.0"
  },
  "paths": {
    "/driver": {
      "delete": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver"
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Driver does not exist",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Token expired",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "403": {
            "description": "Incorrect token",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Unexpected server error",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/driver/refresh": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "auth"
        ],
        "parameters": [
          {
            "description": "Refresh access token",
            "name": "input",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "refresh_token": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Access token",
            "schema": {
              "type": "object",
              "properties": {
                "access_token": {
                  "type": "string"
                },
                "refresh_token": {
                  "type": "string"
                }
              }
            },
            "examples": {
              "properties": {
                "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzUxNjcyODksInVzZXJfaWQiOjF9.gCvkF6ZWJ5c_zA79ILuuEwvkrkn1kOU1Y-Mgr3K2NiM",
                "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Nzc3NTc0OTcsInVzZXJfaWQiOjF9.H5s2JnmjUseUqWFYiLzfYWrlIfa-4dDtd3H2LS5R6IM"
              },
              "type": "object"
            }
          },
          "401": {
            "description": "Token expired",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "403": {
            "description": "Wrong signature",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Unexpected server error",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/driver/sing-in": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "auth"
        ],
        "parameters": [
          {
            "description": "Authentication info",
            "name": "input",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "password": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                },
                "phone_number": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Access token",
            "schema": {
              "type": "object",
              "properties": {
                "access_token": {
                  "type": "string"
                },
                "refresh_token": {
                  "type": "string"
                }
              }
            },
            "examples": {
              "properties": {
                "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzUxNjcyODksInVzZXJfaWQiOjF9.gCvkF6ZWJ5c_zA79ILuuEwvkrkn1kOU1Y-Mgr3K2NiM",
                "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Nzc3NTc0OTcsInVzZXJfaWQiOjF9.H5s2JnmjUseUqWFYiLzfYWrlIfa-4dDtd3H2LS5R6IM"
              },
              "type": "object"
            }
          },
          "400": {
            "description": "Incorrect input data",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "403": {
            "description": "Wrong phone number or password",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Unexpected server error",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/driver/sing-up": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "auth"
        ],
        "summary": "user authentication",
        "parameters": [
          {
            "description": "Authentication info",
            "name": "input",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                },
                "name": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                },
                "password": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                },
                "phone_number": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                },
                "taxi_type": {
                  "type": "string",
                  "required": [
                    "true"
                  ]
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Status of authentication",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Incorrect input data or user already exist",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Unexpected server error",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}`))
}
